export * from "./model.entity"
export * from "./user.entity"
export * from "./residence.entity"
export * from "./category.entity"
export * from "./file.entity"
export * from "./category.property.entity"